[package]
name = "themux"
version = "0.1.0"
edition = "2021"
authors = ["ryanv404"]
description = "CLI app for setting the color theme in Termux."

[dependencies]
bincode = "2.0.0-rc.3"
inquire = "0.6.2"
terminal_size = "0.2.6"
