[package]
name = "themux"
version = "0.1.0"
edition = "2021"
authors = ["ryanv404"]
description = "CLI app that sets the color theme in Termux."

[dependencies]
bincode = "1.3.3"
inquire = "0.6.2"
serde = { version = "1.0.183", features = ["derive"] }
terminal_size = "0.2.6"
